// File generated by flutterfire_cli.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return const FirebaseOptions(
          apiKey: 'AIzaSyCN_eRgwavuwtUvLi6587ztj2rFSOgTiA4',
          appId: '1:295599434565:android:adf90cb59fce15a617ac2c',
          messagingSenderId: '295599434565',
          projectId: 'device-streaming-40403813',
          storageBucket: 'device-streaming-40403813.firebasestorage.app',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are only configured for Android in this project.',
        );
    }
  }
}
