// File generated by flutterfire_cli.
// IMPORTANT: This is a TEMPLATE file. Copy this to firebase_options.dart
// and replace the placeholder values with your actual Firebase configuration.
// DO NOT commit firebase_options.dart to version control!

// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return const FirebaseOptions(
          apiKey: 'YOUR_API_KEY_HERE',
          appId: 'YOUR_APP_ID_HERE',
          messagingSenderId: 'YOUR_MESSAGING_SENDER_ID_HERE',
          projectId: 'YOUR_PROJECT_ID_HERE',
          storageBucket: 'YOUR_STORAGE_BUCKET_HERE',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are only configured for Android in this project.',
        );
    }
  }
}
